version: '3.4'

services:
  customerfeaturesservice:
    image: docker2rahulsingh/customerfeaturesservice
    build:
      context: .
      dockerfile: CustomerFeaturesService/Dockerfile

  customerfeaturesapi:
    image: ${DOCKER_REGISTRY-}customerfeaturesapi
    build:
      context: .
      dockerfile: CustomerFeaturesService/Dockerfile

